#!/usr/bin/env node
/**
 * kubelens init — generate kubelens.config.yaml from the current cluster.
 *
 *   npm run init                 # fails if kubelens.config.yaml exists
 *   npm run init -- --force      # regenerate from scratch
 *   npm run init -- --merge      # refresh CRDs, keep your edits
 *
 * Reads kubelens.default.yaml (the seed: universal built-ins + panel command
 * templates + snapshot table layouts), detects cluster type + registry from
 * kubeconfig/images, lists CRDs via `kubectl api-resources`, and writes a
 * complete, self-sufficient config — built-ins + discovered CRDs + the seed's
 * templates/tables copied in verbatim. The runtime reads only this file; the
 * seed is never loaded at runtime. Discovered CRDs ship `default: []` (off;
 * enable in the visibility panel). Detection logic lives in api/utils/init-detect.ts.
 */

import fs from 'fs';
import path from 'path';
import yaml from 'js-yaml';
import { execFileSync } from 'child_process';
import { parseApiResources } from '../api/utils/api-resources';
import { detectCluster, classifyRegistry, buildCrdEntries, type ResourceEntry } from '../api/utils/init-detect';

const ROOT = path.join(__dirname, '..');
const CONFIG = path.join(ROOT, 'kubelens.config.yaml');
const DEFAULT = path.join(ROOT, 'kubelens.default.yaml');

/** Run kubectl; salvage stdout even on non-zero exit (broken APIServices still list working resources). */
function kubectl(args: string[]): string {
  try {
    return execFileSync('kubectl', args, { encoding: 'utf8', maxBuffer: 10 * 1024 * 1024, stdio: ['ignore', 'pipe', 'pipe'] });
  } catch (e: any) {
    return (e.stdout || '').toString();
  }
}

function main(): void {
  const args = process.argv.slice(2);
  const force = args.includes('--force');
  const merge = args.includes('--merge');

  if (fs.existsSync(CONFIG) && !force && !merge) {
    console.error(`${path.basename(CONFIG)} already exists — use --force to regenerate or --merge to refresh CRDs.`);
    process.exit(1);
  }
  if (!fs.existsSync(DEFAULT)) {
    console.error(`${path.basename(DEFAULT)} not found — cannot build a config without the base template.`);
    process.exit(1);
  }

  const base: any = yaml.load(fs.readFileSync(DEFAULT, 'utf8')) ?? {};
  const exclude = base.discovery?.exclude ?? { groups: [], resources: [] };

  // 1. cluster
  let kc: any = {};
  try { kc = JSON.parse(kubectl(['config', 'view', '--minify', '-o', 'json'])); } catch { /* no kubeconfig */ }
  const cluster = detectCluster(kc);

  // 2. registry — sample deployment images
  const images = kubectl(['get', 'deploy', '-A', '-o', 'jsonpath={..image}']).split(/\s+/).filter(Boolean).slice(0, 30);
  const registry = classifyRegistry(images);

  // 3. CRDs the cluster actually has (skip kinds already in the base built-ins)
  const baseIds = new Set<string>((base.resources ?? []).map((r: any) => `${r.group}/${r.kind}`));
  const discovered = parseApiResources(kubectl(['api-resources', '--verbs=list', '--namespaced=true']));
  const crdEntries = buildCrdEntries(discovered, baseIds, exclude.groups ?? [], exclude.resources ?? []);

  // 4. assemble: built-ins + discovered CRDs
  let resources: ResourceEntry[] = [...(base.resources ?? []), ...crdEntries];
  if (merge && fs.existsSync(CONFIG)) {
    const existing: any = yaml.load(fs.readFileSync(CONFIG, 'utf8')) ?? {};
    const byId = new Map<string, ResourceEntry>(resources.map(r => [`${r.group}/${r.kind}`, r]));
    for (const r of existing.resources ?? []) byId.set(`${r.group}/${r.kind}`, r); // your edits win
    resources = [...byId.values()];
  }

  const cfg = {
    version: '1',
    cluster: { name: cluster.context, type: cluster.type, region: cluster.region, context: cluster.context },
    registry: { type: registry.type },
    resources,
    discovery: base.discovery,
    // Copy the universal panel commands + snapshot table layouts straight from
    // the seed so the generated config is self-sufficient — the runtime reads
    // only kubelens.config.yaml, never the seed.
    templates: base.templates,
    tables: base.tables,
  };

  const header =
    `# Generated by 'npm run init' for ${cluster.type} cluster '${cluster.context}'.\n` +
    `# Discovered CRDs ship default:[] (off) — enable them in the visibility panel.\n` +
    `# Re-run with --merge to refresh CRDs without losing your edits.\n\n`;
  fs.writeFileSync(CONFIG, header + yaml.dump(cfg, { lineWidth: 200 }));

  // summary
  console.log(`context:  ${cluster.context || '(none)'}`);
  console.log(`cluster:  ${cluster.type}${cluster.region ? ` (${cluster.region})` : ''}`);
  console.log(`registry: ${registry.type} (sampled ${images.length} images)`);
  console.log(`CRDs:     ${crdEntries.length} detected (off by default; enable in the panel)`);
  for (const e of crdEntries) console.log(`            - ${e.resourceType}`);
  console.log(`\nwrote ${path.basename(CONFIG)}`);
}

main();
